import { ArrowRight, CalendarDays, Check, ChevronRight, Flag, FolderKanban, Gauge, RotateCcw, Server, SlidersHorizontal, X } from "lucide-react";
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from "react";
import AiraLivingField from "./AiraLivingField";
import type { LivingFieldStats, LivingHomeGeometry, LivingHomeMode, LivingMotionProfile, Point, Rect } from "./livingHomeV2Types";
import "./living-home-v2.css";

const IDLE="/avatar/v1/aira-idle-v1.png",PRESENTING="/avatar/v1/aira-presenting-v1.png";
const initialStats:LivingFieldStats={fps:0,dpr:1,ambientPoints:0,trailSamples:0,packets:0,canvasWidth:0,canvasHeight:0};
const local=(base:DOMRect,rect:DOMRect):Point=>({x:rect.left+rect.width/2-base.left,y:rect.top+rect.height/2-base.top});
const padded=(base:DOMRect,rect:DOMRect,kind:string,pad=14):Rect=>({x:rect.left-base.left-pad,y:rect.top-base.top-pad,width:rect.width+pad*2,height:rect.height+pad*2,kind});

export default function LivingHomeV2Lab(){
 const[mode,setMode]=useState<LivingHomeMode>("default"),[motion,setMotion]=useState<LivingMotionProfile>("normal"),[drawer,setDrawer]=useState(false),[geometry,setGeometry]=useState<LivingHomeGeometry|null>(null),[stats,setStats]=useState(initialStats);const stage=useRef<HTMLElement>(null),avatar=useRef<HTMLDivElement>(null),hand=useRef<HTMLSpanElement>(null),resume=useRef<HTMLElement>(null),mission=useRef<HTMLElement>(null),checkpoint=useRef<HTMLElement>(null),currentTask=useRef<HTMLElement>(null),completion=useRef<HTMLElement>(null),project=useRef<HTMLElement>(null),nextAction=useRef<HTMLElement>(null),runtime=useRef<HTMLElement>(null),offlineStatus=useRef<HTMLDivElement>(null),controls=useRef<HTMLDivElement>(null),panel=useRef<HTMLElement>(null);
 const measure=useCallback(()=>{const root=stage.current,a=avatar.current;if(!root||!a)return;const base=root.getBoundingClientRect(),semanticAnchors:LivingHomeGeometry["semanticAnchors"]={},rects:Rect[]=[];const add=(name:keyof typeof semanticAnchors,element:HTMLElement|null,kind:string)=>{if(!element)return;const rect=element.getBoundingClientRect(),anchorElement=element.querySelector<HTMLElement>("i, b"),anchorRect=anchorElement?.getBoundingClientRect()??rect;semanticAnchors[name]=local(base,anchorRect);rects.push(padded(base,rect,kind));};add("resume",resume.current,"resume");add("mission",mission.current,"mission");add("checkpoint",checkpoint.current,"checkpoint");add("currentTask",currentTask.current,"task");add("completion",completion.current,"completion");add("project",project.current,"project");add("nextAction",nextAction.current,"next-action");add("runtime",runtime.current,"runtime");rects.push(padded(base,a.getBoundingClientRect(),"avatar",20));if(offlineStatus.current)rects.push(padded(base,offlineStatus.current.getBoundingClientRect(),"offline-status",8));if(controls.current)rects.push(padded(base,controls.current.getBoundingClientRect(),"controls",8));if(drawer&&panel.current)rects.push(padded(base,panel.current.getBoundingClientRect(),"drawer",6));setGeometry({width:base.width,height:base.height,avatarAnchor:local(base,hand.current?.getBoundingClientRect()??a.getBoundingClientRect()),semanticAnchors,exclusionRects:rects});},[drawer]);
 useLayoutEffect(()=>{const observer=new ResizeObserver(measure);[stage.current,avatar.current,hand.current,resume.current,mission.current,checkpoint.current,currentTask.current,completion.current,project.current,nextAction.current,runtime.current,offlineStatus.current,controls.current,panel.current].filter(Boolean).forEach(el=>observer.observe(el!));const frame=requestAnimationFrame(measure);return()=>{cancelAnimationFrame(frame);observer.disconnect();};},[measure,mode]);
 useEffect(()=>{[IDLE,PRESENTING].forEach(src=>{const image=new Image();image.src=src;});},[]);useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key.toLowerCase()==="d"&&!(event.target instanceof HTMLInputElement)&&!(event.target instanceof HTMLSelectElement))setDrawer(value=>!value);if(event.key==="Escape")setDrawer(false);};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);
 const avatarSrc=mode==="today"?PRESENTING:IDLE;
 return <section ref={stage} className="living-v2-lab" data-mode={mode} data-motion={motion} data-drawer={drawer||undefined} aria-label="AIRA Living Home V2 visual lab">
  {geometry&&<AiraLivingField mode={mode} motion={motion} geometry={geometry} onStats={setStats}/>}<div className="living-v2-vignette"/><span className="living-v2-label">{mode==="default"?"DEFAULT HOME":mode==="today"?"TODAY FOCUS":mode==="memory"?"MEMORY FOCUS":"OFFLINE HOME"}</span>
  <div ref={avatar} className="living-v2-avatar" aria-hidden="true"><img key={avatarSrc} src={avatarSrc} alt="" draggable={false}/><span ref={hand} className="living-v2-hand-anchor"/></div>
  {(mode==="default"||mode==="offline")&&<><section ref={resume} className="living-v2-resume"><span>Resume point</span><div className="resume-timeline"><article className="is-primary"><i/><small>Latest checkpoint</small><strong>Living Home Phase 1 completed</strong><em>Aug 25, 9:57 PM</em></article><article><i/><small>Current task</small><strong>No active task</strong></article><article><i/><small>Completion</small><strong>Waiting for a task</strong></article></div></section><section ref={mission} className="living-v2-mission"><span>Today’s mission</span><button type="button"><CalendarDays size={17}/>No active task<ArrowRight size={18}/></button></section></>}
  {mode==="today"&&<section className="living-v2-today"><div className="today-guide" aria-hidden="true"/><article ref={checkpoint} className="today-node checkpoint-node"><b><Check size={24}/></b><div><small>Checkpoint</small><strong>Living Home Phase 1 completed</strong><em>Aug 25, 9:57 PM</em></div></article><article ref={currentTask} className="today-node task-node"><b/><div><small>Current task</small><strong>No active task</strong><em>Choose a real task from Projects when you’re ready.</em></div></article><article ref={completion} className="today-node completion-node"><b><Flag size={20}/></b><div><small>Completion</small><strong>Waiting for a task</strong></div></article></section>}
  {mode==="memory"&&<section className="living-v2-memory"><article ref={project} className="memory-node project-node"><b><FolderKanban size={24}/></b><strong>AIRA</strong><span>Structured project</span></article><article ref={checkpoint} className="memory-node memory-checkpoint"><b><Check size={20}/></b><div><small>Latest checkpoint</small><strong>Living Home Phase 1 completed</strong><em>Aug 25, 9:57 PM</em></div></article><article ref={nextAction} className="memory-node memory-action"><b><ChevronRight size={22}/></b><div><small>Next action</small><strong>No active task</strong><em>Choose a real task from Projects when you’re ready.</em></div></article><article ref={runtime} className="memory-node memory-runtime"><b><Server size={20}/></b><div><small>Runtime / source</small><strong>Backend ready</strong><em>qwen2.5:3b</em></div></article></section>}
  {mode==="offline"&&<div ref={offlineStatus} className="living-v2-offline"><span/>Local systems unavailable · semantic activity paused</div>}
  <div ref={controls} className="living-v2-controls"><button type="button" aria-pressed={mode==="default"} onClick={()=>setMode("default")}>Default</button><button type="button" aria-pressed={mode==="today"} onClick={()=>setMode("today")}>Today</button><button type="button" aria-pressed={mode==="memory"} onClick={()=>setMode("memory")}>Memory</button><button type="button" aria-pressed={mode==="offline"} onClick={()=>setMode("offline")}>Offline</button><button type="button" onClick={()=>setDrawer(true)}><SlidersHorizontal size={14}/>Lab</button></div>
  <aside ref={panel} className={`living-v2-panel ${drawer?"is-open":""}`} aria-hidden={!drawer}><header><div><span>Development only</span><h2>Living field</h2></div><button type="button" onClick={()=>setDrawer(false)} aria-label="Close lab controls"><X size={17}/></button></header><label>Motion profile<select value={motion} onChange={event=>setMotion(event.target.value as LivingMotionProfile)}><option value="normal">Normal</option><option value="low-power">Low power</option><option value="reduced-motion">Reduced motion</option></select></label><button className="living-v2-reset" type="button" onClick={()=>{setMode("default");setMotion("normal");}}><RotateCcw size={14}/>Reset</button><div className="living-v2-metrics"><Gauge size={15}/><span><b>FPS</b>{stats.fps}</span><span><b>DPR</b>{stats.dpr.toFixed(2)}</span><span><b>Ambient</b>{stats.ambientPoints}</span><span><b>Samples</b>{stats.trailSamples}</span><span><b>Packets</b>{stats.packets}</span><span><b>Canvas</b>{stats.canvasWidth}×{stats.canvasHeight}</span><span><b>Exclusions</b>{geometry?.exclusionRects.length??0}</span></div><p>Press D to toggle this drawer.</p></aside>
 </section>;
}
