import { useCallback, useEffect, useRef, useState } from "react";
import ChatSignalScene from "../../chat/signal/ChatSignalScene";
import type { ChatSignalPhase, ChatSignalStats, ChatTurn, MotionProfile } from "../../chat/signal/chatSignalTypes";
import ChatSignalDevPanel from "./ChatSignalDevPanel";
import "../../chat/signal/chat-signal.css";
import "./chat-signal-lab.css";

const reply="You left off after completing Living Home Phase 1. The next recommended step is to build the Today experience using your real checkpoint and task data.";
const phases:ChatSignalPhase[]=["user_message","thinking","memory_confirmed","responding","complete"];
const makeTurn=(userMessage:string):ChatTurn=>({id:`lab-${Date.now()}-${Math.random().toString(36).slice(2)}`,userMessage,assistantReply:reply,projectContextUsed:true,intent:"project_question",privacyState:"local",model:"lab",status:"complete",createdAt:new Date().toISOString()});
export default function ChatSignalLab(){const[phase,setPhase]=useState<ChatSignalPhase>("idle"),[mode,setMode]=useState<MotionProfile>("normal"),[open,setOpen]=useState(false),[turns,setTurns]=useState<ChatTurn[]>([]),[active,setActive]=useState<string|null>(null),[stats,setStats]=useState<ChatSignalStats>({fps:0,particles:0,dpr:1,canvasWidth:0,canvasHeight:0});const timer=useRef<number|undefined>();const stop=useCallback(()=>{window.clearTimeout(timer.current);},[]);const run=useCallback(()=>{stop();let index=0;const next=()=>{setPhase(phases[index]);if(index++<phases.length-1)timer.current=window.setTimeout(next,index===2?600:850);};next();},[stop]);const send=useCallback((message:string)=>{const value=message.trim();if(!value)return;const turn=makeTurn(value);setTurns(previous=>[...previous,turn]);setActive(turn.id);run();},[run]);const play=useCallback(()=>{const turn=makeTurn("Where did I leave off?");setTurns(previous=>[...previous,turn]);setActive(turn.id);run();},[run]);const reset=useCallback(()=>{stop();setTurns([]);setActive(null);setPhase("idle");},[stop]);useEffect(()=>()=>stop(),[stop]);useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key.toLowerCase()==="d"&&!(event.target instanceof HTMLTextAreaElement))setOpen(value=>!value);};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[]);return <section className="chat-signal-lab" aria-label="AIRA Chat Signal prototype"><ChatSignalScene phase={phase} messages={turns} activeTurnId={active} isOffline={phase==="offline"} isSending={phase==="thinking"} errorMessage={phase==="error"?"The response signal was interrupted.":undefined} motionProfile={mode} reservedRight={open?358:0} onSend={send} onSelectTurn={setActive} onStats={setStats}/><button className="signal-dev-toggle" type="button" onClick={()=>setOpen(true)}>Lab</button><ChatSignalDevPanel open={open} phase={phase} mode={mode} stats={stats} onClose={()=>setOpen(false)} onPhase={value=>{stop();setPhase(value);}} onMode={setMode} onPlay={play} onReset={reset}/></section>;}
