import { useCallback, useEffect, useRef, useState } from "react";
import { fetchModelStatus, sendMessage, type ModelStatus } from "../../lib/api";
import ChatSignalScene from "./signal/ChatSignalScene";
import type { ChatSignalPhase, ChatTurn } from "./signal/chatSignalTypes";

const pause=(ms:number)=>new Promise<void>(resolve=>window.setTimeout(resolve,ms));
const turnId=()=>`${Date.now()}-${Math.random().toString(36).slice(2)}`;

export default function ChatPage(){
 const[turns,setTurns]=useState<ChatTurn[]>([]),[activeTurnId,setActiveTurnId]=useState<string|null>(null),[phase,setPhase]=useState<ChatSignalPhase>("idle"),[conversationId,setConversationId]=useState<number|null>(null),[modelStatus,setModelStatus]=useState<ModelStatus|null>(null),[sending,setSending]=useState(false),[backendOffline,setBackendOffline]=useState(false),[error,setError]=useState<string|null>(null);const sendingRef=useRef(false),sequence=useRef(0),lastFailed=useRef<string|null>(null);
 useEffect(()=>{let mounted=true;const check=async()=>{try{const status=await fetchModelStatus();if(mounted)setModelStatus(status);}catch{if(mounted)setModelStatus(null);}};void check();const id=window.setInterval(check,10000);return()=>{mounted=false;window.clearInterval(id);sequence.current+=1;};},[]);
 const submit=useCallback(async(message:string)=>{if(sendingRef.current||backendOffline)return;const token=++sequence.current;const turn:ChatTurn={id:turnId(),userMessage:message,status:"pending",createdAt:new Date().toISOString()};sendingRef.current=true;setSending(true);setBackendOffline(false);setError(null);lastFailed.current=message;setTurns(prev=>[...prev,turn]);setActiveTurnId(turn.id);setPhase("user_message");const request=sendMessage({message,conversation_id:conversationId});await pause(320);if(token!==sequence.current)return;setPhase("thinking");try{const response=await request;if(token!==sequence.current)return;setConversationId(response.conversation_id);setTurns(prev=>prev.map(item=>item.id===turn.id?{...item,conversationId:response.conversation_id,assistantReply:response.reply,intent:response.intent,privacyState:response.privacy_state,model:response.model,projectContextUsed:Boolean(response.project_context_used),status:"complete"}:item));if(response.project_context_used){setPhase("memory_confirmed");await pause(520);if(token!==sequence.current)return;}setPhase("responding");await pause(320);if(token!==sequence.current)return;setPhase("complete");lastFailed.current=null;}catch{if(token!==sequence.current)return;setTurns(prev=>prev.map(item=>item.id===turn.id?{...item,status:"error"}:item));setBackendOffline(true);setError("Could not reach the local backend on port 8000.");setPhase("error");}finally{if(token===sequence.current){sendingRef.current=false;setSending(false);}}},[backendOffline,conversationId]);
 const retry=useCallback(()=>{const text=lastFailed.current;if(!text)return;setBackendOffline(false);void submit(text);},[submit]);
 const statusText=phase==="thinking"?"Thinking":phase==="memory_confirmed"?"Project context used":undefined;
 return <div className="chat-page chat-page-signal"><ChatSignalScene phase={backendOffline?"offline":phase} messages={turns} activeTurnId={activeTurnId} statusText={statusText} errorMessage={error??undefined} isOffline={backendOffline} isSending={sending} onSend={message=>void submit(message)} onSelectTurn={id=>{setActiveTurnId(id);setPhase("complete");}} onRetry={retry}/>{modelStatus&&<span className="chat-signal-model" aria-label="Model status">{modelStatus.default_model_available?modelStatus.default_model:"Local model unavailable"}</span>}</div>;
}
